const today = new Date().toISOString().split('T')[0]
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0]

// Age pricing rules (checked in order — first match wins)
export const PRICING_RULES = [
  { label: 'Adult',   minAge: 12,  maxAge: Infinity, multiplier: 1.0 },
  { label: 'Child',   minAge: 5,   maxAge: 11,       multiplier: 0.75 },
  { label: 'Toddler', minAge: 0,   maxAge: 4,        multiplier: 0 },  // free
]

export const LOCATIONS = [
  { label: 'Bangkok (BKK)',       value: 'Bangkok' },
  { label: 'Koh Samui (KSM)',     value: 'Koh Samui' },
  { label: 'Phuket (HKT)',        value: 'Phuket' },
  { label: 'Koh Phi Phi (PPP)',   value: 'Koh Phi Phi' },
  { label: 'Krabi (KBV)',         value: 'Krabi' },
]

export const OPERATORS = [
  { label: 'Lomprayah', value: 'Lomprayah' },
  { label: 'Seatran Ferry', value: 'Seatran Ferry' },
  { label: 'Raja Ferry', value: 'Raja Ferry' },
  { label: 'Songserm Express', value: 'Songserm Express' },
  { label: 'Andaman Wave Master', value: 'Andaman Wave Master' },
  { label: 'Tigerline Travel', value: 'Tigerline Travel' },
]

export const MOCK_TICKETS = [
  {
    id: 1,
    code: 'SF',
    operator: 'Lomprayah',
    type: 'Speed Ferry Premium',
    image: 'https://images.unsplash.com/photo-1559508536-b14e60c6cfe6?w=600&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1559508536-b14e60c6cfe6?w=800&q=80', caption: 'Exterior view' },
      { url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80', caption: 'Ocean view' },
      { url: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80', caption: 'Destination pier' },
    ],
    from: 'Bangkok',
    fromPort: 'Bangkok Pier (BKK)',
    to: 'Koh Samui',
    toPort: 'Koh Samui Pier (KSM)',
    departTime: '11:10',
    arriveTime: '15:45',
    departDate: today,
    departGate: '5',
    arriveGate: '2',
    checkinTime: '30 mins before',
    checkoutTime: '15 mins',
    duration: '4h 35m',
    durationMinutes: 275,
    seats: 45,
    price: 850,
    fee: 50,
    pricing: { adult: 850, child: 640, toddler: 0 },
    amenities: [
      { icon: 'fas fa-wifi', label: 'WiFi' },
      { icon: 'fas fa-utensils', label: 'Food and drinks' },
      { icon: 'fas fa-check-double', label: 'Full amenities' },
    ],
    details: [
      { label: 'Seat', value: 'Premium seat with USB charger' },
      { label: 'Restroom', value: 'VIP restroom' },
      { label: 'Luggage', value: 'Under-seat + overhead storage' },
    ],
    notes: '• Check in 30 minutes before departure • No cancellation after booking • Schedule change is allowed with no additional fee',
  },
  {
    id: 2,
    code: 'CF',
    operator: 'Seatran Ferry',
    type: 'Comfort Ferry',
    image: 'https://images.unsplash.com/photo-1548286978-f218023f8d18?w=600&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1548286978-f218023f8d18?w=800&q=80', caption: 'Exterior view' },
      { url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80', caption: 'Comfortable seating' },
      { url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80', caption: 'Sea route' },
    ],
    from: 'Bangkok',
    fromPort: 'Bangkok Pier (BKK)',
    to: 'Koh Samui',
    toPort: 'Koh Samui Pier (KSM)',
    departTime: '08:55',
    arriveTime: '13:45',
    departDate: today,
    departGate: '3',
    arriveGate: '1',
    checkinTime: '45 mins before',
    checkoutTime: '20 mins',
    duration: '4h 50m',
    durationMinutes: 290,
    seats: 78,
    price: 650,
    fee: 40,
    pricing: { adult: 650, child: 490, toddler: 0 },
    logoColor: 'linear-gradient(135deg, #FFE0B2 0%, #FFD0A0 100%)',
    logoTextColor: 'var(--accent)',
    amenities: [
      { icon: 'fas fa-utensils', label: 'Food and drinks' },
      { icon: 'fas fa-couch', label: 'Comfort seats' },
      { icon: 'fas fa-check-double', label: 'Excellent service' },
    ],
    details: [
      { label: 'Seat', value: 'Reclining seats with entertainment' },
      { label: 'Restroom', value: '2 standard restrooms' },
      { label: 'Meal', value: 'Lunch and snacks included' },
    ],
    notes: '• Check in 45 minutes before departure • Free cancellation up to 24 hours • Free schedule change',
  },
  {
    id: 3,
    code: 'EE',
    operator: 'Raja Ferry',
    type: 'Economy Express',
    image: 'https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=600&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=800&q=80', caption: 'Exterior view' },
      { url: 'https://images.unsplash.com/photo-1499678329028-101435549a4e?w=800&q=80', caption: 'Open deck' },
      { url: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800&q=80', caption: 'Coastline route' },
    ],
    from: 'Bangkok',
    fromPort: 'Bangkok Pier (BKK)',
    to: 'Koh Samui',
    toPort: 'Koh Samui Pier (KSM)',
    departTime: '18:55',
    arriveTime: '22:05',
    departDate: today,
    departGate: '7',
    arriveGate: '4',
    checkinTime: '1 hour before',
    checkoutTime: '30 mins',
    duration: '3h 10m',
    durationMinutes: 190,
    seats: 0,   // SOLD OUT
    price: 450,
    fee: 30,
    pricing: { adult: 450, child: 340, toddler: 0 },
    logoColor: 'linear-gradient(135deg, #E0F2FF 0%, #FFF0E0 100%)',
    logoTextColor: 'var(--accent)',
    amenities: [
      { icon: 'fas fa-toilet', label: 'Restroom' },
      { icon: 'fas fa-user-check', label: 'Onboard support staff' },
    ],
    details: [
      { label: 'Seat', value: 'Standard seat' },
      { label: 'Restroom', value: '1 shared restroom' },
    ],
    notes: '• Check in 1 hour before departure • Limited seats available • Shared restroom',
  },
  {
    id: 4,
    code: 'NF',
    operator: 'Songserm Express',
    type: 'Speed Ferry Premium',
    image: 'https://images.unsplash.com/photo-1494783367193-149034c05e8f?w=600&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1494783367193-149034c05e8f?w=800&q=80', caption: 'Night ferry exterior' },
      { url: 'https://images.unsplash.com/photo-1566438480900-0609be27a4be?w=800&q=80', caption: 'Sleeping berth' },
      { url: 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800&q=80', caption: 'Night at sea' },
    ],
    from: 'Bangkok',
    fromPort: 'Bangkok Pier (BKK)',
    to: 'Koh Samui',
    toPort: 'Koh Samui Pier (KSM)',
    departTime: '22:00',
    arriveTime: '06:00',
    departDate: today,
    departGate: '1',
    arriveGate: '3',
    checkinTime: '1 hour before',
    checkoutTime: '30 mins',
    duration: '8h 00m',
    durationMinutes: 480,
    seats: 120,
    price: 380,
    fee: 25,
    pricing: { adult: 380, child: 285, toddler: 0 },
    logoColor: 'linear-gradient(135deg, #1A237E 0%, #283593 100%)',
    logoTextColor: '#fff',
    amenities: [
      { icon: 'fas fa-bed', label: 'Sleeping berths' },
      { icon: 'fas fa-utensils', label: 'Food and drinks' },
      { icon: 'fas fa-wifi', label: 'WiFi' },
    ],
    details: [
      { label: 'Cabin', value: 'Shared 4-berth cabin' },
      { label: 'Meal', value: 'Dinner + breakfast' },
      { label: 'Luggage', value: 'Storage compartment' },
    ],
    notes: '• Check in 1 hour before departure • Free cancellation up to 48 hours • Pillow and blanket included',
  },
  {
    id: 5,
    code: 'PF',
    operator: 'Andaman Wave Master',
    type: 'Speed Ferry Premium',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80', caption: 'Speed ferry' },
      { url: 'https://images.unsplash.com/photo-1559508536-b14e60c6cfe6?w=800&q=80', caption: 'Andaman sea' },
      { url: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80', caption: 'Koh Phi Phi pier' },
    ],
    from: 'Phuket',
    fromPort: 'Rassada Pier (HKT)',
    to: 'Koh Phi Phi',
    toPort: 'Phi Phi Pier (PPP)',
    departTime: '09:00',
    arriveTime: '10:30',
    departDate: today,
    departGate: '2',
    arriveGate: '1',
    checkinTime: '30 mins before',
    checkoutTime: '15 mins',
    duration: '1h 30m',
    durationMinutes: 90,
    seats: 0,   // SOLD OUT
    price: 350,
    fee: 20,
    pricing: { adult: 350, child: 265, toddler: 0 },
    logoColor: 'linear-gradient(135deg, #E0F7FA 0%, #B2EBF2 100%)',
    logoTextColor: '#00838F',
    amenities: [
      { icon: 'fas fa-life-ring', label: 'Life jackets' },
      { icon: 'fas fa-user-check', label: 'Safety staff' },
    ],
    details: [
      { label: 'Seat', value: 'Open deck with shade' },
      { label: 'Restroom', value: 'Not available on board' },
    ],
    notes: '• Check in 30 minutes before departure • No cancellation • Weather-dependent schedule',
  },
  {
    id: 6,
    code: 'KF',
    operator: 'Andaman Wave Master',
    type: 'Comfort Ferry',
    image: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800&q=80', caption: 'Exterior view' },
      { url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80', caption: 'Air-conditioned cabin' },
      { url: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&q=80', caption: 'Krabi coastline' },
    ],
    from: 'Phuket',
    fromPort: 'Rassada Pier (HKT)',
    to: 'Krabi',
    toPort: 'Krabi Pier (KBV)',
    departTime: '14:00',
    arriveTime: '16:00',
    departDate: today,
    departGate: '4',
    arriveGate: '2',
    checkinTime: '30 mins before',
    checkoutTime: '15 mins',
    duration: '2h 00m',
    durationMinutes: 120,
    seats: 60,
    price: 280,
    fee: 20,
    pricing: { adult: 280, child: 210, toddler: 0 },
    logoColor: 'linear-gradient(135deg, #E8F5E9 0%, #C8E6C9 100%)',
    logoTextColor: '#388E3C',
    amenities: [
      { icon: 'fas fa-snowflake', label: 'Air-conditioned' },
      { icon: 'fas fa-couch', label: 'Comfort seats' },
    ],
    details: [
      { label: 'Seat', value: 'Air-conditioned cabin' },
      { label: 'Restroom', value: '1 restroom' },
    ],
    notes: '• Check in 30 minutes before departure • Free cancellation up to 24 hours',
  },
  {
    id: 7,
    code: 'EE',
    operator: 'Tigerline Travel',
    type: 'Economy Express',
    image: 'https://images.unsplash.com/photo-1532274402-8f75ce748b48?w=600&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1532274402-8f75ce748b48?w=800&q=80', caption: 'Exterior view' },
      { url: 'https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=800&q=80', caption: 'Ferry deck' },
      { url: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&q=80', caption: 'Phuket-Krabi route' },
    ],
    from: 'Phuket',
    fromPort: 'Rassada Pier (HKT)',
    to: 'Krabi',
    toPort: 'Krabi Pier (KBV)',
    departTime: '07:30',
    arriveTime: '09:15',
    departDate: today,
    departGate: '1',
    arriveGate: '1',
    checkinTime: '30 mins before',
    checkoutTime: '15 mins',
    duration: '1h 45m',
    durationMinutes: 105,
    seats: 90,
    price: 180,
    fee: 15,
    pricing: { adult: 180, child: 135, toddler: 0 },
    logoColor: 'linear-gradient(135deg, #FFF9C4 0%, #FFF59D 100%)',
    logoTextColor: '#F57F17',
    amenities: [
      { icon: 'fas fa-toilet', label: 'Restroom' },
    ],
    details: [
      { label: 'Seat', value: 'Standard seat' },
      { label: 'Restroom', value: '1 restroom' },
    ],
    notes: '• Check in 30 minutes before departure • No refund after booking',
  },
  {
    id: 8,
    code: 'SF',
    operator: 'Lomprayah',
    type: 'Speed Ferry Premium',
    image: 'https://images.unsplash.com/photo-1559508536-b14e60c6cfe6?w=600&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1559508536-b14e60c6cfe6?w=800&q=80', caption: 'Exterior view' },
      { url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80', caption: 'Ocean view' },
      { url: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80', caption: 'Destination pier' },
    ],
    from: 'Bangkok',
    fromPort: 'Bangkok Pier (BKK)',
    to: 'Koh Samui',
    toPort: 'Koh Samui Pier (KSM)',
    departTime: '15:30',
    arriveTime: '19:50',
    departDate: tomorrow,
    departGate: '5',
    arriveGate: '2',
    checkinTime: '30 mins before',
    checkoutTime: '15 mins',
    duration: '4h 20m',
    durationMinutes: 260,
    seats: 30,
    price: 850,
    fee: 50,
    pricing: { adult: 850, child: 640, toddler: 0 },
    amenities: [
      { icon: 'fas fa-wifi', label: 'WiFi' },
      { icon: 'fas fa-utensils', label: 'Food and drinks' },
      { icon: 'fas fa-check-double', label: 'Full amenities' },
    ],
    details: [
      { label: 'Seat', value: 'Premium seat with USB charger' },
      { label: 'Restroom', value: 'VIP restroom' },
      { label: 'Luggage', value: 'Under-seat + overhead storage' },
    ],
    notes: '• Check in 30 minutes before departure • No cancellation after booking • Schedule change is allowed with no additional fee',
  },
]
